routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/ganti-status-alat/{id}/{alat}/{status}', [App\Http\Controllers\HomeController::class, 'gantiStatusAlat']);
Route::get('/beranda', [App\Http\Controllers\HomeController::class, 'index'])->name('beranda');
Route::get('/get-jamur/{id}', [App\Http\Controllers\HomeController::class, 'getDataJamur']);

Route::get('/get-suhu-kelembapan/{id}', [App\Http\Controllers\HomeController::class, 'getDataSuhuDanKelembapan']);

Route::resource('jamur',App\Http\Controllers\JamurController::class);
Route::resource('monitoring-jamur',App\Http\Controllers\MonitoringJamurController::class);
Route::resource('kendali-alat',App\Http\Controllers\KendaliAlatController::class);

app/Models/Jamur.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jamur extends Model
{
    use HasFactory;

    public function monitorings (){
    return $this->hasMany(MonitoringJamur::class);
    }

    public function alats (){
        return $this->hasMany(KendaliAlat::class);
        }
}

app/Http/Controllers/JamurController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jamur;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
class JamurController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $items = Jamur::latest()->get();

            return DataTables::of($items)
                ->addColumn('action', function ($item) {
                    return '
                           <a class="btn-danger btn-sm"  onclick="deleteItem(' . $item->id . ')"><i class="fas fa-trash text-white"></i></span></a> <a class="btn-info btn-sm" href="' . route('jamur.edit',$item->id) . '"><i class="fas fa-pencil-alt text-white    "></i></span></a>';
                })
                ->removeColumn('id')
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('jamur.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('jamur.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $item = new Jamur();
        $item->nama = $request->nama;
        $item->tahap_pertumbuhan = $request->tahap_pertumbuhan;
        $item->tanggal_tanam = $request->tanggal;
        $item->save();
        return redirect('/jamur')->with('success','Data Berhasil Di Simpan');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $data['item'] = Jamur::where('id',$id)->first();
        return view('jamur.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $item = Jamur::where('id',$id)->first();
        $item->nama = $request->nama;
        $item->tahap_pertumbuhan = $request->tahap_pertumbuhan;
        $item->tanggal_tanam = $request->tanggal;
        $item->save();
        return redirect('/jamur')->with('success','Data Berhasil Di Update');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $item = Jamur::where('id',$id)->first();
        $item->delete();
        return response('success');
    }
}

resources/views/jamur/create.blade.php
@extends('layouts.template')
@section('content')
  <div class="row gy-5 g-xl-12">
    <div class="col-xl-12">
      <h1>Manajemen Jamur</h1>
    </div>
    <!--begin::Col-->
    <div class="col-xl-12">
      <!--begin::List Widget 3-->
      <div class="card card-xl-stretch mb-xl-8">
        <div class="card-header border-0">
          <h3 class="card-title fw-bolder">Tambah Data</h3>
        </div>
        <div class="card-body pt-2">
          <form action="{{ route('jamur.store') }}" method="POST">
            @csrf
            <div class="row">
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Nama Jamur</label>
                  <input type="text" class="form-control form-control-solid" name="nama"
                    placeholder="Masukkan Nama Jamur" required />
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Tahap Pertumbuhan</label>
                  <select name="tahap_pertumbuhan" class="form-control form-control-solid" required>
                    <option value="Miselia">Miselia</option>
                    <option value="Primordia">Primordia</option>
                    <option value="Tubuh Buah">Tubuh Buah</option>
                  </select>
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Tanggal Tanam</label>
                  <input type="date" class="form-control form-control-solid" name="tanggal" required />
                </div>
              </div>
            </div>

            <button type="submit" href="#" class="btn btn-success">Simpan</button>
            <a href="/jamur" class="btn btn-secondary">Kembali</a>
          </form>
          <!--begin::Datatable-->

          <!--end:Item-->
        </div>
        <!--end::Body-->
      </div>
      <!--end:List Widget 3-->
    </div>
    <!--end::Col-->
  </div>
@endsection

@push('js')
  <script></script>
@endpush

resources/views/jamur/edit.blade.php
@extends('layouts.template')
@section('content')
  <div class="row gy-5 g-xl-12">
    <div class="col-xl-12">
      <h1>Manajemen Jamur</h1>
    </div>
    <!--begin::Col-->
    <div class="col-xl-12">
      <!--begin::List Widget 3-->
      <div class="card card-xl-stretch mb-xl-8">
        <div class="card-header border-0">
          <h3 class="card-title fw-bolder">Ubah Data</h3>
        </div>
        <div class="card-body pt-2">
         <form action="{{ route('jamur.update',$item->id) }}" method="POST">
            @csrf
            @method('PATCH')
            <div class="row">
                <div class="col-12">
                  <div class="fv-row mb-8 fv-plugins-icon-container">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold mb-2">Nama Jamur</label>
                    <input type="text" class="form-control form-control-solid" name="nama" value="{{ $item->nama }}"
                      placeholder="Masukkan Nama Jamur" required />
                  </div>
                </div>
                <div class="col-12">
                    <div class="fv-row mb-8 fv-plugins-icon-container">
                      <!--begin::Label-->
                      <label class="required fs-6 fw-bold mb-2">Tahap Pertumbuhan</label>
                      <select name="tahap_pertumbuhan" class="form-control form-control-solid" required>
                        <option value="Miselia" @if($item->tahap_pertumbuhan=='Miselia') selected @endif>Miselia</option>
                        <option value="Primordia" @if($item->tahap_pertumbuhan=='Primordia') selected @endif>Primordia</option>
                        <option value="Tubuh Buah"  @if($item->tahap_pertumbuhan=='Tubuh Buah') selected @endif>Tubuh Buah</option>
                      </select>
                    </div>
                  </div>
                <div class="col-12">
                  <div class="fv-row mb-8 fv-plugins-icon-container">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold mb-2">Tanggal Tanam</label>
                    <input type="date" class="form-control form-control-solid" name="tanggal" value="{{ $item->tanggal_tanam }}" required />
                  </div>
                </div>
              </div>

              <button type="submit" href="#" class="btn btn-success">Simpan</button>
              <a href="/jamur" class="btn btn-secondary">Kembali</a>
         </form>
          <!--begin::Datatable-->

          <!--end:Item-->
        </div>
        <!--end::Body-->
      </div>
      <!--end:List Widget 3-->
    </div>
    <!--end::Col-->
  </div>
@endsection

@push('js')
  <script></script>
@endpush

resources/views/jamur/index.blade.php
@extends('layouts.template')
@section('content')
  <div class="row gy-5 g-xl-12">
    <div class="col-xl-12">
      <h1>Manajemen Jamur</h1>
    </div>
    <!--begin::Col-->
    <div class="col-xl-12">
      <!--begin::List Widget 3-->
      <div class="card card-xl-stretch mb-xl-8">
        <div class="card-body pt-2">

          <!--begin::Datatable-->
          <table id="datatable" class="table align-middle table-row-dashed fs-6 gy-5">
            <thead>
              <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                <th>
                  No.
                </th>
                <th>Nama Jamur</th>
                <th>Tahap Pertumbuhan</th>
                <th>Tanggal Tanam</th>
                <th class="text-end min-w-100px">Actions</th>
              </tr>
            </thead>
            <tbody class="text-gray-600 fw-bold">

            </tbody>
          </table>
          <!--end:Item-->
        </div>
        <!--end::Body-->
      </div>
      <!--end:List Widget 3-->
    </div>
    <!--end::Col-->
  </div>
@endsection

@push('js')
  <script>
    let dataTable = $('#datatable').DataTable({
            dom: 'lBfrtip',
            buttons: [{
                className: 'btn btn-success btn-sm mr-2',
                text: 'Create',
                action: function (e, dt, node, config) {
                    window.location.href = "{{ route('jamur.create') }}";
                }
            }, {
                className: 'btn btn-warning btn-sm mr-2',
                text: 'Reload',
                action: function (e, dt, node, config) {
                    reloadDatatable();
                    Toast.fire({
                        icon: 'success',
                        title: 'Reload'
                    })
                }
            }],
            responsive: true,
            processing: true,
            serverSide: true,
            searching: true,
            pageLength: 5,
            lengthMenu: [
                [5, 10, 15, -1],
                [5, 10, 15, "All"]
            ],
            ajax: {
                url: '/jamur',
                type: 'GET',
            },
            columns: [{
                    data: 'DT_RowIndex',
                    orderable: false
                },
                {
                    data: 'nama',
                    orderable: true
                },
                {
                    data: 'tahap_pertumbuhan',
                    orderable: true
                },
                {
                    data: 'tanggal_tanam',
                    orderable: true
                },
                {
                    data: 'action',
                    name: '#',
                    orderable: false
                },
            ]
        });

        function reloadDatatable() {
            dataTable.ajax.reload();
        }
        let child_url = '/jamur';
  </script>
@endpush