routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/ganti-status-alat/{id}/{alat}/{status}', [App\Http\Controllers\HomeController::class, 'gantiStatusAlat']);
Route::get('/beranda', [App\Http\Controllers\HomeController::class, 'index'])->name('beranda');
Route::get('/get-jamur/{id}', [App\Http\Controllers\HomeController::class, 'getDataJamur']);

Route::get('/get-suhu-kelembapan/{id}', [App\Http\Controllers\HomeController::class, 'getDataSuhuDanKelembapan']);

Route::resource('jamur',App\Http\Controllers\JamurController::class);
Route::resource('monitoring-jamur',App\Http\Controllers\MonitoringJamurController::class);
Route::resource('kendali-alat',App\Http\Controllers\KendaliAlatController::class);

app/Models/KendaliAlat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class KendaliAlat extends Model
{
    use HasFactory;
    public function jamur (){
    return $this->belongsTo(Jamur::class);
    }
}

app/Http/Controllers/KendaliAlatController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jamur;
use App\Models\KendaliAlat;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
class KendaliAlatController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $items = KendaliAlat::latest()->with('jamur')->get();

            return DataTables::of($items)
                ->addColumn('action', function ($item) {
                    return '
                           <a class="btn-danger btn-sm"  onclick="deleteItem(' . $item->id . ')"><i class="fas fa-trash text-white"></i></span></a> <a class="btn-info btn-sm" href="' . route('kendali-alat.edit',$item->id) . '"><i class="fas fa-pencil-alt text-white    "></i></span></a>';
                })
                ->removeColumn('id')
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('kendali-alat.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $data['jamur'] = Jamur::orderBy('nama')->get();
        return view('kendali-alat.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $item = new KendaliAlat();
        $item->nama_alat = $request->nama_alat;
        $item->jamur_id = $request->jamur_id;
        $item->tahap_pertumbuhan = $request->tahap_pertumbuhan;
        $item->jam = $request->jam;
        $item->suhu_min = $request->suhu_min;
        $item->suhu_max = $request->suhu_max;
        $item->kelembapan_udara_min = $request->kelembapan_udara_min;
        $item->kelembapan_udara_max = $request->kelembapan_udara_max;
        $item->save();
        return redirect('/kendali-alat')->with('success','Data Berhasil Di Simpan');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $data['item'] = KendaliAlat::where('id',$id)->first();
        $data['jamurs'] = Jamur::orderBy('nama')->get();
        return view('kendali-alat.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $item = KendaliAlat::where('id',$id)->first();
        $item->nama_alat = $request->nama_alat;
        $item->jamur_id = $request->jamur_id;
        $item->tahap_pertumbuhan = $request->tahap_pertumbuhan;
        $item->jam = $request->jam;
        $item->suhu_min = $request->suhu_min;
        $item->suhu_max = $request->suhu_max;
        $item->kelembapan_udara_min = $request->kelembapan_udara_min;
        $item->kelembapan_udara_max = $request->kelembapan_udara_max;
        $item->save();
        return redirect('/kendali-alat')->with('success','Data Berhasil Di Update');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $item = KendaliAlat::where('id',$id)->first();
        $item->delete();
        return response('success');
    }
}

resources/views/kendali-alat/create.blade.php
@extends('layouts.template')
@section('content')
  <div class="row gy-5 g-xl-12">
    <div class="col-xl-12">
      <h1>Kendali Alat</h1>
    </div>
    <!--begin::Col-->
    <div class="col-xl-12">
      <!--begin::List Widget 3-->
      <div class="card card-xl-stretch mb-xl-8">
        <div class="card-header border-0">
          <h3 class="card-title fw-bolder">Tambah Data</h3>
        </div>
        <div class="card-body pt-2">
          <form action="{{ route('kendali-alat.store') }}" method="POST">
            @csrf
            <div class="row">
                <div class="col-12">
                    <div class="fv-row mb-8 fv-plugins-icon-container">
                      <!--begin::Label-->
                      <label class="required fs-6 fw-bold mb-2">Jamur</label>
                      <select name="jamur_id" class="form-control form-control-solid" required>
                        <option value selected disabled>==Pilih Salah Satu==</option>
                        @foreach ($jamur as $item)
                            <option value="{{ $item->id }}" >{{ $item->nama }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Nama Alat</label>
                  <input type="text" class="form-control form-control-solid" name="nama_alat"
                    placeholder="Masukkan Nama Alat" required />
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Tahap Pertumbuhan</label>
                  <select name="tahap_pertumbuhan" class="form-control form-control-solid" required>
                    <option value="Miselia">Miselia</option>
                    <option value="Primordia">Primordia</option>
                    <option value="Tubuh Buah">Tubuh Buah</option>
                  </select>
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Suhu Minimum</label>
                  <input type="number" class="form-control form-control-solid" name="suhu_min" value="0" step="0.01" required />
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Suhu Maksimum</label>
                  <input type="number" class="form-control form-control-solid" name="suhu_max" value="0" step="0.01" required />
                </div>
              </div>

               <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Kelembapan Udara Minimum</label>
                  <input type="number" class="form-control form-control-solid" name="kelembapan_udara_min" value="0" step="0.01" required />
                </div>
              </div>

              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Kelembapan Udara Maksimum</label>
                  <input type="number" class="form-control form-control-solid" name="kelembapan_udara_max" value="0" step="0.01"  required />
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Jam</label>
                  <input type="time" class="form-control form-control-solid"  name="jam" required />
                </div>
              </div>
            </div>

            <button type="submit" href="#" class="btn btn-success">Simpan</button>
            <a href="{{ route('kendali-alat.index') }}" class="btn btn-secondary">Kembali</a>
          </form>
          <!--begin::Datatable-->

          <!--end:Item-->
        </div>
        <!--end::Body-->
      </div>
      <!--end:List Widget 3-->
    </div>
    <!--end::Col-->
  </div>
@endsection

@push('js')
  <script></script>
@endpush

resources/views/kendali-alat/edit.blade.php
@extends('layouts.template')
@section('content')
  <div class="row gy-5 g-xl-12">
    <div class="col-xl-12">
      <h1>Kendali Alat</h1>
    </div>
    <!--begin::Col-->
    <div class="col-xl-12">
      <!--begin::List Widget 3-->
      <div class="card card-xl-stretch mb-xl-8">
        <div class="card-header border-0">
          <h3 class="card-title fw-bolder">Ubah Data</h3>
        </div>
        <div class="card-body pt-2">
          <form action="{{ route('kendali-alat.update',$item->id) }}" method="POST">
            @csrf
            @method('PATCH')
            <div class="row">
                <div class="col-12">
                    <div class="fv-row mb-8 fv-plugins-icon-container">
                      <!--begin::Label-->
                      <label class="required fs-6 fw-bold mb-2">Jamur</label>
                      <select name="jamur_id" class="form-control form-control-solid" required>
                        <option value selected disabled>==Pilih Salah Satu==</option>
                        @foreach ($jamurs as $jamur)
                            <option value="{{ $jamur->id }}" @if($jamur->id == $item->jamur_id) selected @endif >{{ $jamur->nama }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Nama Alat</label>
                  <input type="text" class="form-control form-control-solid" name="nama_alat"
                    placeholder="Masukkan Nama Alat" required value="{{ $item->nama_alat }}" />
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Tahap Pertumbuhan</label>
                  <select name="tahap_pertumbuhan" class="form-control form-control-solid" required>
                    <option value="Miselia" @if($item->tahap_pertumbuhan=='Miselia') selected @endif>Miselia</option>
                    <option value="Primordia" @if($item->tahap_pertumbuhan=='Primordia') selected @endif>Primordia</option>
                    <option value="Tubuh Buah"  @if($item->tahap_pertumbuhan=='Tubuh Buah') selected @endif>Tubuh Buah</option>
                  </select>
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Suhu Minimum</label>
                  <input type="number" class="form-control form-control-solid" name="suhu_min"  step="0.01" value="{{ $item->suhu_min }}" required />
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Suhu Maksimum</label>
                  <input type="number" class="form-control form-control-solid" name="suhu_max"  step="0.01" value="{{ $item->suhu_max }}" required />
                </div>
              </div>

               <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Kelembapan Udara Minimum</label>
                  <input type="number" class="form-control form-control-solid" name="kelembapan_udara_min"  step="0.01" value="{{ $item->kelembapan_udara_min }}" required />
                </div>
              </div>

              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Kelembapan Udara Maksimum</label>
                  <input type="number" class="form-control form-control-solid" name="kelembapan_udara_max"  step="0.01"   value="{{ $item->kelembapan_udara_max }}" required />
                </div>
              </div>
              <div class="col-12">
                <div class="fv-row mb-8 fv-plugins-icon-container">
                  <!--begin::Label-->
                  <label class="required fs-6 fw-bold mb-2">Jam</label>
                  <input type="time" class="form-control form-control-solid"  value="{{ $item->jam }}"  name="jam" required />
                </div>
              </div>
            </div>

            <button type="submit" href="#" class="btn btn-success">Simpan</button>
            <a href="{{ route('kendali-alat.index') }}" class="btn btn-secondary">Kembali</a>
          </form>
          <!--begin::Datatable-->

          <!--end:Item-->
        </div>
        <!--end::Body-->
      </div>
      <!--end:List Widget 3-->
    </div>
    <!--end::Col-->
  </div>
@endsection

@push('js')
  <script></script>
@endpush

resources/views/kendali-alat/index.blade.php
@extends('layouts.template')
@section('content')
  <div class="row gy-5 g-xl-12">
    <div class="col-xl-12">
      <h1>Kendali Alat</h1>
    </div>
    <!--begin::Col-->
    <div class="col-xl-12">
      <!--begin::List Widget 3-->
      <div class="card card-xl-stretch mb-xl-8">
        <div class="card-body pt-2">
          <!--begin::Datatable-->
          <table id="datatable" class="table align-middle table-row-dashed fs-6 gy-5">
            <thead>
              <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                <th>
                  No.
                </th>
                <th>Nama Alat</th>
                <th>Nama Jamur</th>
                <th>Tahap Pertumbuhan</th>
                <th>Suhu Min</th>
                <th>Suhu Max</th>
                <th>Kelembapan Udara Min</th>
                <th>Kelembapan Udara Max</th>
                <th>Jam</th>
                <th class="text-end min-w-100px">Actions</th>
              </tr>
            </thead>
            <tbody class="text-gray-600 fw-bold">

            </tbody>
          </table>
          <!--end:Item-->
        </div>
        <!--end::Body-->
      </div>
      <!--end:List Widget 3-->
    </div>
    <!--end::Col-->
  </div>
@endsection

@push('js')
  <script>
    let dataTable = $('#datatable').DataTable({
            dom: 'lBfrtip',
            buttons: [{
                className: 'btn btn-success btn-sm mr-2',
                text: 'Create',
                action: function (e, dt, node, config) {
                    window.location.href = "{{ route('kendali-alat.create') }}";
                }
            }, {
                className: 'btn btn-warning btn-sm mr-2',
                text: 'Reload',
                action: function (e, dt, node, config) {
                    reloadDatatable();
                    Toast.fire({
                        icon: 'success',
                        title: 'Reload'
                    })
                }
            }],
            responsive: true,
            processing: true,
            serverSide: true,
            searching: true,
            pageLength: 5,
            lengthMenu: [
                [5, 10, 15, -1],
                [5, 10, 15, "All"]
            ],
            ajax: {
                url: '{{ route("kendali-alat.index") }}',
                type: 'GET',
            },
            columns: [{
                    data: 'DT_RowIndex',
                    orderable: false
                },
                  {
                    data: 'nama_alat',
                    orderable: true
                },
                {
                    data: 'jamur.nama',
                    orderable: true
                },
                {
                    data: 'tahap_pertumbuhan',
                    orderable: true
                },
                {
                    data: 'suhu_min',
                    orderable: true
                },
                {
                    data: 'suhu_max',
                    orderable: true
                },
                {
                    data: 'kelembapan_udara_min',
                    orderable: true
                },
                {
                    data: 'kelembapan_udara_max',
                    orderable: true
                },
                {
                    data: 'jam',
                    orderable: true
                },
                {
                    data: 'action',
                    name: '#',
                    orderable: false
                },
            ]
        });

        function reloadDatatable() {
            dataTable.ajax.reload();
        }
        let child_url = '{{ route("kendali-alat.index") }}';
  </script>
@endpush