routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/ganti-status-alat/{id}/{alat}/{status}', [App\Http\Controllers\HomeController::class, 'gantiStatusAlat']);
Route::get('/beranda', [App\Http\Controllers\HomeController::class, 'index'])->name('beranda');
Route::get('/get-jamur/{id}', [App\Http\Controllers\HomeController::class, 'getDataJamur']);

Route::get('/get-suhu-kelembapan/{id}', [App\Http\Controllers\HomeController::class, 'getDataSuhuDanKelembapan']);

Route::resource('jamur',App\Http\Controllers\JamurController::class);
Route::resource('monitoring-jamur',App\Http\Controllers\MonitoringJamurController::class);
Route::resource('kendali-alat',App\Http\Controllers\KendaliAlatController::class);

app/Models/MonitoringJamur.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MonitoringJamur extends Model
{
    use HasFactory;

    public function jamur (){
    return $this->belongsTo(Jamur::class);
    }
}

app/Http/Controllers/MonitoringJamurController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jamur;
use App\Models\MonitoringJamur;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
class MonitoringJamurController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            if($request->filter == 'Semua Jamur'){
                $items = MonitoringJamur::latest()->with('jamur')->get();

            }else{
                $filter = $request->filter;
                $items = MonitoringJamur::latest()->whereHas('jamur',function($q) use ($filter){
                     $q->where('id',$filter);
                })->with('jamur')->get();
            }

            return DataTables::of($items)
                ->addColumn('action', function ($item) {
                    return '
                           <a class="btn-danger btn-sm"  onclick="deleteItem(' . $item->id . ')"><i class="fas fa-trash text-white"></i></span></a>';
                })
                ->editColumn('suhu',function($item){
                    return $item->suhu . ' &deg;C';
                })
                ->editColumn('kelembapan_udara',function($item){
                    return $item->kelembapan_udara . '%';
                })
                ->editColumn('status_kipas',function($item){
                    if($item->status_kipas==1){
                        $message = 'Aktif';
                        $status = 'success';
                    }else{
                        $message = 'Non Aktif';
                        $status = 'secondary';
                    }
                    return "<span class='badge badge-$status'>$message</span>";
                })
                ->editColumn('status_mist_maker',function($item){
                    if($item->status_mist_maker==1){
                        $message = 'Aktif';
                        $status = 'success';
                    }else{
                        $message = 'Non Aktif';
                        $status = 'secondary';
                    }
                    return "<span class='badge badge-$status'>$message</span>";
                })
                ->editColumn('status_tirai',function($item){
                    if($item->status_tirai==1){
                        $message = 'Aktif';
                        $status = 'success';
                    }else{
                        $message = 'Non Aktif';
                        $status = 'secondary';
                    }
                    return "<span class='badge badge-$status'>$message</span>";
                })
                ->editColumn('status_lampu',function($item){
                    if($item->status_lampu==1){
                        $message = 'Aktif';
                        $status = 'success';
                    }else{
                        $message = 'Non Aktif';
                        $status = 'secondary';
                    }
                    return "<span class='badge badge-$status'>$message</span>";
                })
                ->removeColumn('id')
                ->addIndexColumn()
                ->rawColumns(['action','suhu','status_kipas','status_mist_maker','status_tirai','status_lampu'])
                ->make(true);
        }
        $data['jamur'] = Jamur::orderBy('nama')->get();
        return view('monitoringJamur.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('monitoringJamur.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $item = new MonitoringJamur();
        $item->nama = $request->nama;
        $item->tanggal_tanam = $request->tanggal;
        $item->save();
        return redirect('/monitoring-jamur')->with('success','Data Berhasil Di Simpan');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $data['jamurs'] = Jamur::orderBy('nama')->get();
        $data['item'] = MonitoringJamur::where('id',$id)->first();
        return view('monitoringJamur.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $item = MonitoringJamur::where('id',$id)->first();
        $item->nama = $request->nama;
        $item->tanggal_tanam = $request->tanggal;
        $item->save();
        return redirect('/monitoring-jamur')->with('success','Data Berhasil Di Update');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $item = MonitoringJamur::where('id',$id)->first();
        $item->delete();
        return response('success');
    }
}

resources/views/monitoringJamur/edit.blade.php
@extends('layouts.template')
@section('content')
  <div class="row gy-5 g-xl-12">
    <div class="col-xl-12">
      <h1>Monitoring Jamur</h1>
    </div>
    <!--begin::Col-->
    <div class="col-xl-12">
      <!--begin::List Widget 3-->
      <div class="card card-xl-stretch mb-xl-8">
        <div class="card-header border-0">
          <h3 class="card-title fw-bolder">Ubah Data</h3>
        </div>
        <div class="card-body pt-2">
         <form action="{{ route('jamur.update',$item->id) }}" method="POST">
            @csrf
            @method('PATCH')
            <div class="row">
                <div class="col-12">
                    <div class="fv-row mb-8 fv-plugins-icon-container">
                      <!--begin::Label-->
                      <label class="required fs-6 fw-bold mb-2">Pilih Jamur</label>
                      <select name="tahap_pertumbuhan" class="form-control form-control-solid" required>
                        @foreach ($jamurs as $jamurs)
                        <option value="Miselia" @if($item->jamur_id==$jamur->id) selected @endif>{{ $jamur->nama }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                <div class="col-12">
                  <div class="fv-row mb-8 fv-plugins-icon-container">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold mb-2">Suhu</label>
                    <input type="number" class="form-control form-control-solid" name="suhu" value="{{ $item->suhu }}" required />
                  </div>
                  <div class="col-12">
                    <div class="fv-row mb-8 fv-plugins-icon-container">
                      <!--begin::Label-->
                      <label class="required fs-6 fw-bold mb-2">Kelembapan Udara</label>
                      <input type="number" class="form-control form-control-solid" name="kelembapan_udara" value="{{ $item->kelembapan_udara }}" required />
                    </div>
                </div>
              </div>

              <button type="submit" href="#" class="btn btn-success">Simpan</button>
              <a href="/jamur" class="btn btn-secondary">Kembali</a>
         </form>
          <!--begin::Datatable-->

          <!--end:Item-->
        </div>
        <!--end::Body-->
      </div>
      <!--end:List Widget 3-->
    </div>
    <!--end::Col-->
  </div>
@endsection

@push('js')
  <script></script>
@endpush

resources/views/monitoringJamur/index.blade.php
@extends('layouts.template')
@section('content')
  <div class="row gy-5 g-xl-12">
    <div class="col-xl-12">
      <h1>Monitoring Jamur</h1>
    </div>
    <!--begin::Col-->
    <div class="col-xl-12">
      <!--begin::List Widget 3-->
      <div class="card card-xl-stretch mb-xl-8">
        <div class="card-body pt-2">
          <h4 for="" class="mt-4">Filter Jamur</h4>
          <div class="filter d-flex col-4">
            <select class="form-control form-control-solid" id="filter-jamur" aria-label="Select example">
              <option selected>Semua Jamur</option>
              @foreach ($jamur as $item)
                <option value="{{ $item->id }}">{{ $item->nama }}</option>
              @endforeach
            </select>
          </div>
          <!--begin::Datatable-->
          <table id="datatable" class="table align-middle table-row-dashed fs-6 gy-5">
            <thead>
              <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                <th>
                  No.
                </th>
                <th>Nama Jamur</th>
                <th>Suhu</th>
                <th>Kelembapan Udara</th>
                <th>Tahap Pertumbuhan</th>
                <th>Status Kipas</th>
                <th>Status Mist Maker</th>
                <th>Status Lampu</th>
                <th>Status Tirai</th>
                <th>Waktu</th>
                <th class="text-end min-w-100px">Actions</th>
              </tr>
            </thead>
            <tbody class="text-gray-600 fw-bold">

            </tbody>
          </table>
          <!--end:Item-->
        </div>
        <!--end::Body-->
      </div>
      <!--end:List Widget 3-->
    </div>
    <!--end::Col-->
  </div>
@endsection

@push('js')
  <script>
    let jamur =$('#filter-jamur').val();
    let dataTable = $('#datatable').DataTable({
      dom: 'lBfrtip',
      buttons: [{
        className: 'btn btn-warning btn-sm mr-2',
        text: 'Reload',
        action: function(e, dt, node, config) {
          reloadDatatable();
          Toast.fire({
            icon: 'success',
            title: 'Reload'
          })
        }
      }],
      responsive: true,
      processing: true,
      serverSide: true,
      searching: true,
      pageLength: 5,
      lengthMenu: [
        [5, 10, 15, -1],
        [5, 10, 15, "All"]
      ],
      ajax: {
        url: "{{ route('monitoring-jamur.index') }}",
        type: 'GET',
        data: {
            'filter': function () {
                        return jamur;
                    }
        }
      },
      columns: [{
          data: 'DT_RowIndex',
          orderable: false
        },
        {
          data: 'jamur.nama',
          orderable: true
        },
        {
          data: 'suhu',
          orderable: true
        },
        {
          data: 'kelembapan_udara',
          orderable: true
        },
        {
          data: 'status_kipas',
          orderable: true
        },
        {
          data: 'status_mist_maker',
          orderable: true
        },
        {
          data: 'status_lampu',
          orderable: true
        },
        {
          data: 'status_tirai',
          orderable: true
        },
        {
          data: 'tahap_pertumbuhan',
          orderable: true
        },
        {
          data: 'waktu',
          orderable: true
        },
        {
          data: 'action',
          name: '#',
          orderable: false
        },
      ]
    });

    function reloadDatatable() {
      dataTable.ajax.reload();
    }

    $('#filter-jamur').on('change',function(){
        console.log($('#filter-jamur').val())
        jamur =$('#filter-jamur').val();
        dataTable.draw();
    })
    let child_url = "{{ route('monitoring-jamur.index') }}";
  </script>
@endpush